language: java
sudo: false
dist: xenial

before_script:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

jobs:
  include:
    - stage: OpenJDK 11.0.3
      env: JDK=11 + Hotspot
      jdk: openjdk11
      script:
      - source install-jdk.sh --url https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.3%2B7/OpenJDK11U-jdk_x64_linux_hotspot_11.0.3_7.tar.gz
      - mvn --version
      - export
      - mvn clean test -Dtest="BadClientAuthenticationTCPChainedProxyTest"

cache:
  directories:
    - $HOME/.m2