language: java
sudo: false
dist: xenial

jobs:
  include:
    - stage: OpenJDK 11.0.3
      env: JDK=11 + Hotspot
      jdk: openjdk11
      script:
      - mvn --version
      - export
      - mvn clean test -Dtest="BadClientAuthenticationTCPChainedProxyTest"

cache:
  directories:
    - $HOME/.m2
